using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UBL_FRMS.Classes.Constant
{
    public static class GeneralConstants
    {
        public static string RECORD_UPDATED_MESSAGE = "$.msgBox({title:'Record Successfuly Updated',type:'info',content:'The record has been successfully updated'});";
        public static string RECORD_FOUND = "$.msgBox({title:'Record Found',type:'info',content:'Please click on the link below to view Membership details'});";
        public static string RECORD_NOT_FOUND = "$.msgBox({title:'Record Found',type:'error',content:'Incorrect PersonalID/Could not find membership details with entered Personal ID'});";
        public static string EXCEPTION_OCCURED = "$.msgBox({title:'Record Found',type:'error',content:'Exception has been occured into the system. some of the form fields hasn't been saved'});";

        public static string workflowNameCPCRequest = "CPC Request Workflow";
        public static string workflowNameCPCAgenda = "CPC Agenda Workflow";

        public static string Draft = "Draft";
        public static string Save = "Save";
        public static string Update = "Update";
        public static string Delete = "Delete";
        public static string AutoGeneratedNo = "Auto Generated Number";

        public const string HomePageUrl = "/Pages/Home.aspx";

        public static string ChoiceColumnDisplay = "Display";
        public static string ChoiceColumnValue = "Value";
        public static string DataTableDisplayField = "Display";
        public static string DataTableValueField = "Value";
        public static string ListFieldTypeField = "FieldType";
        public static string DateFormat = "dd-MM-yyy";

        //Made by talha
        public static string DateFormatRequestForm = "MM-dd-yyy";
        public static string DateTimeFormat = "dddd, MMMM d, yyyy hh:mm";
        public static string NotificationDateFormat = "d MMM yyyy";
        public static string CAMLDateTimeFormat = "yyyy-MM-dd";
        public static string CPCMemberGroup = "CPC Members";
        public static string CPCAdminGroup = "CPC Admin";
        public static string CPCCoordinatorGroup = "CPC Coordinator";
        public static string CPCCommitteeGroup = "CPC Committee";

        // Development 
        //public static int SendBacktoInitiator = 3;
        //public static int SendtoCPCCoordinator = 2002;
        //public static int ForwardtoCPC = 1003;
        public static int Submit = 4;
        public static int Approve = 1;
        public static int Reject = 2;

        // Production
        //public static int SendBacktoInitiator = 2;
        //public static int SendtoCPCCoordinator = 1;
        //public static int ForwardtoCPC = 3;
        //public static int Submit = 4;
        //public static int Approve = 5;
        //public static int Reject = 6;

        public static string CPCRequestPermissionMessage = "You don't have permissions to add CPC Request. Please contact your application administrator.";
        public static string CPCRequestDraftMessage = "CPC Request has been drafted successfully.";
        public static string CPCRequestSaveErrorMessage = "CPC Request cannot be saved due to some issue. Please contact your application administrator.";
        public static string CPCRequestSaveMessage = "CPC Request has been saved successfully.";

        ////////////////TRC RELATED CONFIGURATIONS////////////////
        public static string TRCRequiredMessage = "Select TRC ID from below LOV or to fill new TRC, click ";
        public static string TRCHyperlink = "http://tdl-epm2012:90/PWA/Pages/TRCRequestForm.aspx";
        public static string TRCWebApplicationURL = "http://tdl-epm2012:90/";
        public static string TRCSiteCollectionURL = "http://tdl-epm2012:90/PWA";
        public static string TRCListName = "TRC Request";
        public static string TRCDataValueField = "ID";
        public static string TRCDataTextField = "Title";
        public static string TRCDataRequestSummaryField = "RequestSummary";
        public static string TRCDataCombinedField = "Combined";
        public static string TRCQuery = "<Where><And><Eq><FieldRef Name='Author' /><Value Type='Integer'><UserID/></Value></Eq><Or><Eq><FieldRef Name='Status' /><Value Type='Choice'>Approved</Value></Eq><Eq><FieldRef Name='Status' /><Value Type='Choice'>Conditional Approved</Value></Eq></Or></And></Where>";

        public static string TRCViewByIDLink = "http://tdl-epm2012:90/PWA/Pages/TRCRequestForm.aspx?itemID=";
        ///////////////////////////////////////////////////////////

        public static string TaskCompletedMessage = "Task has already been completed.";
        public static string TaskNotAuthorizedMessage = "you are not authorized to perform this action.";

        public static string CPCAgendaPermissionMessage = "You don't have permissions to add CPC Agenda. Please contact your application administrator.";
        public static string CPCAgendaDraftMessage = "CPC Agenda has been drafted successfully.";
        public static string CPCAgendaSaveErrorMessage = "CPC Agenda cannot be saved due to some issue. Please contact your application administrator.";
        public static string CPCAgendaSaveMessage = "CPC Agenda has been saved successfully.";

        public static string CPCRowEmptyMessage = "You cannot proceed without adding CPC Request(s) in CPC Agenda.";
        public static string CPCRecordAlreadyExistMessage = "Your Selected CPC is already exists.";
    }
}
